set nobackup 
set nocp
set noeol
set softtabstop=4
set tabstop=4
set shiftwidth=4
set et
set ignorecase
set hlsearch

set ai
set ruler
set showcmd
set incsearch
set dir=$temp       " Make swap live in the %TEMP% directory
syn on
set guifont=Lucida_Console:h10:cANSI:qDRAFT

" Load the color scheme
if has('gui_running')
    colo inkpot
else    
    colo default
    hi Normal ctermbg=black ctermfg=white
endif

" Setup some common abbreviations 
iabbrev #c //==============================================================================

" Filetype settings
filetype plugin on
filetype indent on

" Source a Couple of scripts
source ~\vimfiles\matchit.vim
source ~\vimfiles\plugin\fswitch.vim

function SetPowershellOptions()
    set softtabstop=2
    set tabstop=2
    set shiftwidth=2
endfunction
au FileType ps1 call SetPowershellOptions()

function SetYamlOptions()
    set softtabstop=2
    set tabstop=2
    set shiftwidth=2
endfunction
au FileType yaml call SetYamlOptions()
