#
# Module manifest for module 'Midori'
#
# Generated by: Jared Parsons
#
# Generated on: 10/6/2010
#

@{

ModuleToProcess = 'Midori.psm1'
ModuleVersion = '1.0'
GUID = '4a03d9cb-25bc-4903-8458-c9db95fbe541'
Author = 'Jared Parsons'
Copyright = '(c) 2010 Jared Parsons. All rights reserved.'
Description = 'Functions specific to Midori'
RequiredModules = @('Common')
NestedModules = @() 
FunctionsToExport = '*'
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'
ModuleList = @()
FileList = @()

}

