#
# Module manifest for module 'Configure'
#
# Generated by: Jared Parsons
#
# Generated on: 10/6/2010
#

@{

ModuleToProcess = 'Configuration.psm1'
ModuleVersion = '1.0'
GUID = 'e48fa2f1-aa3d-432d-ac0c-0353a4016514'
Author = 'Jared Parsons'
Copyright = '(c) 2010 Jared Parsons. All rights reserved.'
Description = 'Allow for machine configuration'
NestedModules = 'Common.psm1'
FunctionsToExport = '*'
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'
ModuleList = @()
FileList = @()

}

