#
# Module manifest for module 'MSharpExtra'
#
# Generated by: Jared Parsons
#
# Generated on: 10/6/2012
#

@{

ModuleToProcess = 'MSharpExtra.psm1'
ModuleVersion = '1.0'
GUID = '6d8e6204-def3-4b78-8b35-ae7d1e09a7b5'
Author = 'Jared Parsons'
Copyright = '(c) 2010 Jared Parsons. All rights reserved.'
Description = 'M# Functions '
RequiredModules = @('Common', 'MidoriCommon')
NestedModules = @() 
FunctionsToExport = '*'
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'
ModuleList = @()
FileList = @()

}

