
#
# Module manifest for module 'MidoriCommon'
#
# Generated by: Jared Parsons
#
# Generated on: 10/6/2012
#

@{

ModuleToProcess = 'MidoriCommon.psm1'
ModuleVersion = '1.0'
GUID = '78690d78-6ee1-4bc2-8ce2-e2c0a742ec1a'
Author = 'Jared Parsons'
Copyright = '(c) 2010 Jared Parsons. All rights reserved.'
Description = 'Functions common to Midori'
RequiredModules = @('Common')
NestedModules = @() 
FunctionsToExport = '*'
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'
ModuleList = @()
FileList = @()

}

